import React,{useEffect,useState} from 'react';
import {dateTypes,formatDate} from './date.mjs';
import './admin.css';
async function api(url,body){const r=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||'请求失败');return d;}
const empty=()=>({name:'',original:'',regions:['日本'],periodIds:[],date:{type:'unknown',start:'',end:'',approx:false,part:''},source:'',description:'',medium:'TV动画',nature:'真实历史背景',image:'',imageSource:'',width:0,height:0,evidenceUrl:'',evidence:'',notes:'',status:'draft'});
export default function Admin(){
 const [session,SS]=useState(null),[db,D]=useState(null),[error,E]=useState(''),[notice,N]=useState(''),[password,Pass]=useState(''),[busy,B]=useState(false),[query,Q]=useState(''),[filter,F]=useState('all'),[region,R]=useState('all'),[edit,W]=useState(null),[dirty,Dirty]=useState(false),[preview,Preview]=useState(false),[confirm,C]=useState(null),[history,H]=useState(false);
 async function load(){try{SS(await api('/api/session'));}catch(e){E(e.message);}}
 useEffect(()=>{load();},[]);
 useEffect(()=>{if(session?.authenticated)api('/api/admin').then(D).catch(e=>E(e.message));},[session]);
 useEffect(()=>{const guard=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 useEffect(()=>{if(!edit&&!confirm)return;const panel=document.querySelector(confirm?'.cms-confirm [role=alertdialog]':'.cms-editor');const before=document.activeElement;panel?.querySelector('button,input,select,textarea')?.focus();const key=e=>{if(e.key==='Escape'){e.preventDefault();if(confirm)C(null);else if(!dirty)W(null);}if(e.key==='Tab'&&panel){const items=[...panel.querySelectorAll('button:not(:disabled),input,select,textarea,a')].filter(el=>el.getClientRects().length);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);before?.focus();};},[!!edit,!!confirm]);
 const change=(key,value)=>{W(w=>({...w,[key]:value}));Dirty(true);};
 function open(w){if(dirty){C({label:'放弃未保存修改？',run:()=>{W(w);Dirty(false);Preview(false);}});}else{W(w);Preview(false);}E('');N('');}
 async function login(e){e.preventDefault();B(true);E('');try{await api(session.setup?'/api/setup':'/api/login',{password});Pass('');await load();}catch(e){E(e.message);}finally{B(false);}}
 async function save(action,work=edit){B(true);E('');N('');try{const result=await api('/api/work',{action,work,revision:db.revision});D(result);if(['trash','restore'].includes(action))W(null);else W(result.works.find(x=>x.id===work.id)||result.works.find(x=>x.name===work.name));Dirty(false);N({save:'草稿已保存，前台保持原发布版本',publish:'已发布，前台将在刷新后显示',unpublish:'已撤下，前台不再显示',trash:'已移入回收站',restore:'已恢复为草稿'}[action]);}catch(e){E(e.message);}finally{B(false);C(null);}}
 async function upload(file){if(!file)return;if(file.size>5*1024*1024){E('图片不能超过5MB');return;}B(true);E('');try{const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});const im=new Image();im.src=data;await im.decode();const result=await api('/api/upload',{data});W(w=>({...w,image:result.image,width:im.naturalWidth,height:im.naturalHeight}));Dirty(true);}catch(e){E(e.message||'图片读取失败');}finally{B(false);}}
 const periodList=edit?db?.periods.filter(p=>edit.periodIds.includes(p.id))||[]:[];
 const field=(key,label,type='text')=><label>{label}<input type={type} value={edit[key]} onChange={e=>change(key,e.target.value)}/></label>;
 if(!session||session.authenticated&&!db)return <div className="cms"><p>{error||'正在加载管理面板…'}</p></div>;
 if(!session.authenticated)return <div className="cms cms-login"><form onSubmit={login}><div className="cms-eyebrow">ANITIME / CONTENT STUDIO</div><h1>{session.setup?'设置管理员':'登录管理面板'}</h1><p>独立维护作品、年代与封面。管理入口不出现在对外页面。</p><label>{session.setup?'创建密码（至少10位）':'管理员密码'}<input type="password" autoComplete={session.setup?'new-password':'current-password'} minLength="10" maxLength="200" value={password} onChange={e=>Pass(e.target.value)} required/></label>{error&&<p role="alert" className="cms-error">{error}</p>}<button className="cms-primary" disabled={busy}>{busy?'请稍候…':session.setup?'设置并进入':'登录'}</button><small>本机管理服务 · 密码加密保存</small></form></div>;
 const rows=db.works.filter(w=>(filter==='trash'?w.status==='trash':w.status!=='trash')&&(filter==='all'||filter==='trash'||(filter==='published'?!!w.published:!w.published))&&(region==='all'||w.regions.includes(region))&&`${w.name} ${w.original}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="cms"><div className="cms-top"><a href="/admin" className="cms-brand">ANITIME <span>内容管理</span></a><div><a href="/" target="_blank" rel="noreferrer">查看前台 ↗</a><button onClick={()=>H(!history)}>修改记录</button><button onClick={async()=>{if(dirty){E('请先保存或关闭编辑后退出');return;}await api('/api/logout',{});D(null);await load();}}>退出登录</button></div></div><div className="cms-heading"><div><div className="cms-eyebrow">YOUR ANIME LIBRARY</div><h1>作品库 <span>{db.works.filter(w=>w.status!=='trash').length}</span></h1><p>统一维护作品信息，草稿与公开展示相互独立。</p></div><button className="cms-primary" onClick={()=>open(empty())}>＋ 新增作品</button></div>
 {notice&&<div className="cms-notice" role="status">{notice}</div>}{error&&<div className="cms-error" role="alert">{error}<button onClick={()=>{if(!dirty)api('/api/admin').then(D).catch(e=>E(e.message));else E('请先保留未保存内容，再关闭编辑并重新加载');}}>重新加载数据</button></div>}
 <div className="cms-tools"><input aria-label="搜索作品" placeholder="搜索中文名或日文原名…" value={query} onChange={e=>Q(e.target.value)}/><select aria-label="地域筛选" value={region} onChange={e=>R(e.target.value)}><option value="all">全部地域</option>{db.regions.map(r=><option key={r}>{r}</option>)}</select><div className="cms-tabs">{[['all','全部'],['published','已发布'],['draft','草稿'],['trash','回收站']].map(([value,label])=><button aria-pressed={filter===value} key={value} onClick={()=>F(value)}>{label}</button>)}</div></div>
 <div className="cms-table-wrap"><table><thead><tr><th>作品</th><th>地域 / 时期</th><th>年代</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map(w=><tr key={w.id}><td><button className="cms-work" onClick={()=>open({...w})}>{w.image?<img src={w.image} alt=""/>:<div className="cms-no-image">无封面</div>}<span><b>{w.name}</b><small>{w.original||'原名待补充'}</small></span></button></td><td>{w.regions.join(' / ')}<small>{db.periods.filter(p=>w.periodIds.includes(p.id)).map(p=>p.name).join('、')}</small></td><td>{formatDate(w.date,db.periods.filter(p=>w.periodIds.includes(p.id)))}</td><td><span className="cms-status">{w.status==='trash'?'已删除':w.published?'已发布':'草稿'}</span></td><td>{w.status==='trash'?<button disabled={busy} onClick={()=>save('restore',w)}>恢复为草稿</button>:<><button onClick={()=>open({...w})}>编辑</button><button className="cms-delete" onClick={()=>C({label:`将《${w.name}》移入回收站？前台将同步撤下，之后可以恢复。`,run:()=>save('trash',w)})}>删除</button></>}</td></tr>)}</tbody></table>{!rows.length&&<p className="cms-empty">没有符合条件的作品</p>}</div>
 {history&&<aside className="cms-history"><button onClick={()=>H(false)}>关闭记录 ×</button><h2>最近修改</h2>{!(db.history||[]).length&&<p>暂无修改记录</p>}{(db.history||[]).map((h,i)=><p key={i}><b>{h.name}</b><br/>{({save:'保存草稿',publish:'发布',unpublish:'撤下',trash:'删除',restore:'恢复'})[h.action]} · {new Date(h.at).toLocaleString('zh-CN')}</p>)}</aside>}
 {edit&&<div className="cms-overlay"><section className="cms-editor" role="dialog" aria-modal="true" aria-label="编辑作品"><div className="cms-editor-head"><div><small>{edit.id?'EDIT WORK':'NEW WORK'}</small><h2>{edit.name||'新增作品'}{dirty&&<sup>未保存</sup>}</h2></div><button aria-label="关闭编辑" onClick={()=>open(null)}>×</button></div><div className="cms-editor-scroll"><div className="cms-editor-tabs"><button aria-pressed={!preview} onClick={()=>Preview(false)}>编辑信息</button><button aria-pressed={preview} onClick={()=>Preview(true)}>展示预览</button></div>{preview?<div className="cms-preview">{edit.image&&<img src={edit.image} alt={edit.name}/>}<div><small>{edit.regions.join(' / ')} · {periodList.map(p=>p.name).join(' / ')}</small><h2>{edit.name||'作品名称'}</h2><strong>{formatDate(edit.date,periodList)}</strong><p>{edit.description||'尚未填写介绍'}</p><small>时间线位置：{periodList.map(p=>`${p.name}（${p.range}）`).join('、')||'请选择时期'}</small><p>当前预览未保存内容，不会自动发布。</p></div></div>:<><h3>基本信息</h3><div className="cms-fields">{field('name','中文名 *')}{field('original','日文原名')}<label>类型<select value={edit.medium} onChange={e=>change('medium',e.target.value)}>{['TV动画','剧场版','网络动画','OVA'].map(x=><option key={x}>{x}</option>)}</select></label><label>背景性质<select value={edit.nature} onChange={e=>change('nature',e.target.value)}>{['真实历史背景','历史改写','架空'].map(x=><option key={x}>{x}</option>)}</select></label></div><fieldset><legend>地域 *</legend>{db.regions.map(r=><label className="cms-check" key={r}><input type="checkbox" checked={edit.regions.includes(r)} onChange={e=>{const regions=e.target.checked?[...edit.regions,r]:edit.regions.filter(x=>x!==r);W(w=>({...w,regions,periodIds:w.periodIds.filter(id=>db.periods.some(p=>p.id===id&&regions.includes(p.region)))}));Dirty(true);}}/>{r}</label>)}</fieldset><fieldset><legend>历史时期 *</legend>{db.periods.filter(p=>edit.regions.includes(p.region)).map(p=><label key={p.id} className="cms-check"><input type="checkbox" checked={edit.periodIds.includes(p.id)} onChange={e=>change('periodIds',e.target.checked?[...edit.periodIds,p.id]:edit.periodIds.filter(id=>id!==p.id))}/>{p.region} · {p.name}</label>)}</fieldset>
 <h3>年代</h3><div className="cms-fields"><label>年代类型<select value={edit.date.type} onChange={e=>change('date',{type:e.target.value,start:'',end:'',approx:false,part:''})}>{Object.entries(dateTypes).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>{['year','range','decade','century'].includes(edit.date.type)&&<label>{edit.date.type==='century'?'世纪数':edit.date.type==='decade'?'年代起点（例如1940）':'起始年份（公元前用负数）'}<input type="number" value={edit.date.start??''} onChange={e=>change('date',{...edit.date,start:e.target.value})}/></label>}{edit.date.type==='range'&&<label>结束年份<input type="number" value={edit.date.end??''} onChange={e=>change('date',{...edit.date,end:e.target.value})}/></label>}{edit.date.type==='century'&&<label>世纪阶段<select value={edit.date.part||''} onChange={e=>change('date',{...edit.date,part:e.target.value})}>{['','前期','中期','后期'].map(p=><option value={p} key={p}>{p||'整体'}</option>)}</select></label>}</div>{!['unknown','period'].includes(edit.date.type)&&<label className="cms-check"><input type="checkbox" checked={!!edit.date.approx} onChange={e=>change('date',{...edit.date,approx:e.target.checked})}/>大约，非确切年份</label>}<div className="cms-date-preview">前台显示 <b>{formatDate(edit.date,periodList)}</b></div>
 <h3>介绍与依据</h3><label>无剧透的历史背景介绍<textarea rows="4" value={edit.description} onChange={e=>change('description',e.target.value)}/></label>{field('source','官方链接','url')}{field('evidenceUrl','年代依据链接','url')}<label>年代依据摘录<textarea rows="2" value={edit.evidence} onChange={e=>change('evidence',e.target.value)}/></label><label>内部备注（不公开）<textarea rows="2" value={edit.notes} onChange={e=>change('notes',e.target.value)}/></label>
 <h3>封面</h3><div className="cms-cover">{edit.image?<img src={edit.image} alt="封面预览"/>:<div>尚未添加封面</div>}<label>上传图片<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files[0])}/><small>PNG / JPEG / WebP，最大5MB。自动识别横竖比例。</small></label></div>{field('imageSource','图片来源链接','url')}</>}{error&&<p className="cms-error" role="alert">{error}</p>}{notice&&<p role="status" className="cms-notice">{notice}</p>}</div><div className="cms-editor-footer"><span>{edit.published?'前台已有发布版本':'当前尚未公开'}</span>{edit.published&&<button disabled={busy} onClick={()=>save('unpublish')}>撤下</button>}<button disabled={busy||edit.status==='trash'} onClick={()=>save('save')}>保存草稿</button><button className="cms-primary" disabled={busy||edit.status==='trash'} onClick={()=>save('publish')}>{busy?'处理中…':'保存并发布'}</button></div></section></div>}
 {confirm&&<div className="cms-confirm"><div role="alertdialog" aria-modal="true" aria-label="确认操作"><h2>{confirm.label}</h2><button disabled={busy} onClick={()=>C(null)}>取消</button><button className="cms-primary" disabled={busy} onClick={()=>{const fn=confirm.run;C(null);fn();}}>确认</button></div></div>}
 </div>;
}
