import {resolveAsset} from './asset.mjs';
import React,{useEffect,useRef} from 'react';
import './work-detail.css';
export function WorkDetail({selected,region,onClose,onFilter,activeSeries}) {
 const dialog=useRef(null),opener=useRef(document.activeElement);
 useEffect(()=>{const node=dialog.current;node.showModal();return()=>{node.close();if(opener.current?.isConnected)opener.current.focus({preventScroll:true});};},[]);
 const portrait=selected.height>selected.width;
 return <dialog ref={dialog} className="detail" onCancel={onClose} aria-label="作品詳情"><button className="close" aria-label="關閉詳情" onClick={onClose} autoFocus><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg></button><div className="modal-grid"><div className="modal-image"><div className={'poster '+(portrait?'portrait':'landscape')}><img src={resolveAsset(selected.image)} alt={selected.name+'官方宣傳圖'}/></div></div><article><p className="meta">{region} / {selected.period}</p><h2>{selected.name}</h2><div className="red-rule"/><strong className="detail-year">{selected.date}</strong>{selected.edition&&<p className="detail-edition">{selected.edition}</p>}{selected.seriesId&&onFilter&&<button className="series-link" onClick={()=>onFilter(selected)}>{activeSeries===selected.seriesId?'返回':selected.seriesName+'系列 ↗'}</button>}<p className="description">{selected.description}</p>{selected.date==='UNKNOWN'&&<p className="description">具體年份 UNKNOWN。</p>}<p className="detail-medium">{selected.medium}</p>{selected.source&&<a className="official-cta" href={selected.source} target="_blank" rel="noreferrer"><span className="official-cta-labels"><span className="official-cta-label official-cta-label-out">訪問官網</span><span className="official-cta-label official-cta-label-in" aria-hidden="true">訪問官網</span></span><span className="official-cta-icon" aria-hidden="true"><svg viewBox="0 0 38 20">{[0,9,18,27].flatMap((offset,i)=>[[-6,3],[-2,6],[2,10],[-2,14],[-6,17]].map(([x,y],j)=><circle key={i+'-'+j} className={'arrow-dot arrow-dot-'+i} style={{'--dot-delay':((3-i)*70+Math.abs(2-j)*40)+'ms'}} cx={offset+x-1} cy={y} r=".85"/>))}</svg></span></a>}</article></div></dialog>;
}
