import {resolveAsset} from './asset.mjs';
import React,{useEffect,useRef,useState} from 'react';
import './work-detail.css';
function centuryLabel(date){if(!date||date.start==null||date.start===''||!['year','range','decade','century'].includes(date.type)||!Number.isFinite(Number(date.start)))return '年代未明确';const start=Number(date.start);if(date.type==='century')return `${start<0?'公元前':''}${Math.abs(start)}世纪`;const label=year=>`${year<0?'公元前':''}${Math.ceil(Math.abs(year)/100)}世纪`;const end=date.type==='range'?Number(date.end):date.type==='decade'?start+9:start;return Number.isFinite(end)&&label(start)!==label(end)?`${label(start)}—${label(end)}`:label(start);}
export function WorkDetail({selected,region,onClose,onFilter,activeSeries}) {
 const dialog=useRef(null),opener=useRef(document.activeElement);
 const [layout,setLayout]=useState('original');
 useEffect(()=>{const node=dialog.current;node.showModal();return()=>{node.close();if(opener.current?.isConnected)opener.current.focus({preventScroll:true});};},[]);
 const portrait=selected.height>selected.width;
 return <dialog ref={dialog} className={'detail '+(layout==='reference'?'reference-detail':'original-detail')} onCancel={onClose} aria-label="作品详情"><div className="detail-layout-switch" role="group" aria-label="详情排版"><button aria-pressed={layout==='original'} onClick={()=>setLayout('original')}>原版</button><button aria-pressed={layout==='reference'} onClick={()=>setLayout('reference')}>参考版</button></div><button className="close" aria-label="关闭详情" onClick={onClose} autoFocus><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg></button>{layout==='original'?<div className="modal-grid"><div className="modal-image"><div className={'poster '+(portrait?'portrait':'landscape')}><img src={resolveAsset(selected.image)} alt={selected.name+'官方宣传图'}/></div></div><article><p className="meta">{region} / {selected.period}</p><h2>{selected.name}</h2><div className="red-rule"/><strong className="detail-year">{selected.date}</strong>{selected.edition&&<p className="detail-edition">{selected.edition}</p>}{selected.seriesId&&onFilter&&<button className="series-link" onClick={()=>onFilter(selected)}>{activeSeries===selected.seriesId?'返回':selected.seriesName+'系列 ↗'}</button>}<p className="description">{selected.description}</p>{selected.date==='UNKNOWN'&&<p className="description">具体年份 UNKNOWN。</p>}<dl><div><dt>MEDIUM</dt><dd>{selected.medium}</dd></div><div><dt>IMAGE SOURCE</dt><dd><a href={selected.source} target="_blank" rel="noreferrer">官方 / 发行方页面 ↗</a></dd></div></dl></article></div>:<div className="reference-sheet"><p className="ref-brand">ANITIME</p><div className="ref-heading"><h2>{selected.name}</h2>{selected.edition&&<p>{selected.edition}</p>}</div><figure className={'ref-image '+(portrait?'portrait':'landscape')}><img src={resolveAsset(selected.image)} alt={selected.name+'官方宣传图'}/></figure><section className="ref-story"><strong>{selected.date==='UNKNOWN'?'年代未明确':selected.date}</strong><p>{selected.description}</p>{selected.seriesId&&onFilter&&<button className="series-link" onClick={()=>onFilter(selected)}>{activeSeries===selected.seriesId?'返回':selected.seriesName+'系列 ↗'}</button>}</section><aside className="ref-top"><span>{selected.medium}</span><span>{region}</span><span>{selected.period}</span></aside><div className="ref-century">{centuryLabel(selected.dateData)}</div><div className="ref-bottom"><div><p>{region} / {selected.period}</p><span>{selected.medium}</span></div><a href={selected.source} target="_blank" rel="noreferrer" aria-label="官方 / 发行方页面"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-5-5 5 5-5 5"/></svg></a></div></div>}</dialog>;
}
